# Generated by Django 5.1.4 on 2024-12-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_question_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="buzzer",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
