# Generated by Django 5.1.4 on 2024-12-31 21:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_player_buzzer"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True, default="", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
