# Generated by Django 5.1.4 on 2024-12-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_team_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["game", "order"]},
        ),
        migrations.AddField(
            model_name="question",
            name="special",
            field=models.BooleanField(default=False),
        ),
    ]
