# Generated by Django 5.1.4 on 2024-12-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_alter_board_options_question_special"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["category", "order", "points"]},
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
