# Generated by Django 5.1.15 on 2025-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_question_options_alter_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="score_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="state_version",
            field=models.IntegerField(default=0),
        ),
    ]
