# Generated by Django 5.1.15 on 2025-12-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_player_score_version_question_state_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="points_term",
            field=models.CharField(default="points", max_length=50),
        ),
    ]
