# Generated by Django 5.1.15 on 2025-12-30 03:17

from django.db import migrations, models


def convert_special_to_flags(apps, schema_editor):
    Question = apps.get_model("game", "Question")
    for question in Question.objects.all():
        question.flags = ["dino"] if question.special else []
        question.save()


def convert_flags_to_special(apps, schema_editor):
    Question = apps.get_model("game", "Question")
    for question in Question.objects.all():
        question.special = "dino" in question.flags
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_game_points_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="flags",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(convert_special_to_flags, convert_flags_to_special),
        migrations.RemoveField(
            model_name="question",
            name="special",
        ),
    ]
