# Generated by Django 5.1.15 on 2025-12-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_replace_special_with_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="media_answer_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
