# Generated by Django 5.1.15 on 2025-12-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_add_media_answer_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="media_answer_url",
        ),
        migrations.RemoveField(
            model_name="question",
            name="media_url",
        ),
        migrations.AddField(
            model_name="question",
            name="slides",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("text", "Text Only"), ("slides", "Slides")], default="text", max_length=6
            ),
        ),
    ]
