# Generated by Django 5.1.15 on 2025-12-30 23:37

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_refactor_to_slides"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="type",
        ),
        migrations.AlterField(
            model_name="question",
            name="slides",
            field=models.JSONField(
                blank=True, default=list, validators=[game.models.validate_slides]
            ),
        ),
    ]
