# Generated by Django 5.1.15 on 2025-12-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_remove_type_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="flags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
