# Generated by Django 5.1.15 on 2026-01-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_alter_question_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
